
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int slash = 35;
  public static final int admira = 11;
  public static final int guinB = 37;
  public static final int ampersand = 16;
  public static final int flecha = 3;
  public static final int Allav = 39;
  public static final int tilde = 42;
  public static final int letra = 5;
  public static final int numeral = 13;
  public static final int comDob = 12;
  public static final int comSim = 17;
  public static final int acentoG = 38;
  public static final int simSeparacion = 4;
  public static final int menos = 23;
  public static final int mayorQ = 30;
  public static final int EOF = 0;
  public static final int dosp = 26;
  public static final int porsentaje = 15;
  public static final int pyc = 27;
  public static final int mas = 21;
  public static final int error = 1;
  public static final int barra = 41;
  public static final int entero = 6;
  public static final int Cllav = 40;
  public static final int por = 20;
  public static final int punto = 24;
  public static final int str = 10;
  public static final int potencia = 36;
  public static final int id = 8;
  public static final int Cpar = 19;
  public static final int conj = 2;
  public static final int arroba = 32;
  public static final int salto = 43;
  public static final int dolar = 14;
  public static final int tExtraer = 44;
  public static final int eq = 29;
  public static final int menorQ = 28;
  public static final int Apar = 18;
  public static final int interroga = 31;
  public static final int corC = 34;
  public static final int corA = 33;
  public static final int div = 25;
  public static final int cma = 22;
  public static final int decimal = 7;
  public static final int cadena = 9;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "conj",
  "flecha",
  "simSeparacion",
  "letra",
  "entero",
  "decimal",
  "id",
  "cadena",
  "str",
  "admira",
  "comDob",
  "numeral",
  "dolar",
  "porsentaje",
  "ampersand",
  "comSim",
  "Apar",
  "Cpar",
  "por",
  "mas",
  "cma",
  "menos",
  "punto",
  "div",
  "dosp",
  "pyc",
  "menorQ",
  "eq",
  "mayorQ",
  "interroga",
  "arroba",
  "corA",
  "corC",
  "slash",
  "potencia",
  "guinB",
  "acentoG",
  "Allav",
  "Cllav",
  "barra",
  "tilde",
  "salto",
  "tExtraer"
  };
}

